-- 用户表添加扩展字段
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(32) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS qq VARCHAR(32) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS real_name_status VARCHAR(16) DEFAULT 'none';
ALTER TABLE users ADD COLUMN IF NOT EXISTS real_name VARCHAR(128) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS id_card VARCHAR(32) DEFAULT '';
