-- 修复 products 表 schema：将旧字段替换为 min/max/custom_mode/tiers 结构

-- 删除旧字段
ALTER TABLE products DROP COLUMN IF EXISTS vcpu;
ALTER TABLE products DROP COLUMN IF EXISTS vcpu_allow_custom;
ALTER TABLE products DROP COLUMN IF EXISTS memory_mb;
ALTER TABLE products DROP COLUMN IF EXISTS memory_allow_custom;
ALTER TABLE products DROP COLUMN IF EXISTS disk_mb;
ALTER TABLE products DROP COLUMN IF EXISTS disk_allow_custom;
ALTER TABLE products DROP COLUMN IF EXISTS data_disk_default_mb;
ALTER TABLE products DROP COLUMN IF EXISTS data_disk_allow_custom;
ALTER TABLE products DROP COLUMN IF EXISTS network_down_mbps;
ALTER TABLE products DROP COLUMN IF EXISTS network_up_mbps;
ALTER TABLE products DROP COLUMN IF EXISTS network_allow_custom;
ALTER TABLE products DROP COLUMN IF EXISTS network_unit_price_cents;
ALTER TABLE products DROP COLUMN IF EXISTS traffic_limit_gb;

-- CPU 配置
ALTER TABLE products ADD COLUMN IF NOT EXISTS vcpu_min INT NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS vcpu_max INT NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS vcpu_custom_mode VARCHAR(16) NOT NULL DEFAULT 'unlimited';
ALTER TABLE products ADD COLUMN IF NOT EXISTS vcpu_tiers JSONB NOT NULL DEFAULT '[]';
ALTER TABLE products ADD COLUMN IF NOT EXISTS vcpu_unit_price_cents BIGINT NOT NULL DEFAULT 0;

-- 内存配置
ALTER TABLE products ADD COLUMN IF NOT EXISTS memory_min_mb INT NOT NULL DEFAULT 1024;
ALTER TABLE products ADD COLUMN IF NOT EXISTS memory_max_mb INT NOT NULL DEFAULT 1024;
ALTER TABLE products ADD COLUMN IF NOT EXISTS memory_custom_mode VARCHAR(16) NOT NULL DEFAULT 'unlimited';
ALTER TABLE products ADD COLUMN IF NOT EXISTS memory_tiers JSONB NOT NULL DEFAULT '[]';
ALTER TABLE products ADD COLUMN IF NOT EXISTS memory_unit_price_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS memory_unit VARCHAR(4) NOT NULL DEFAULT 'mb';

-- 系统盘配置
ALTER TABLE products ADD COLUMN IF NOT EXISTS disk_min_mb INT NOT NULL DEFAULT 10240;
ALTER TABLE products ADD COLUMN IF NOT EXISTS disk_max_mb INT NOT NULL DEFAULT 10240;
ALTER TABLE products ADD COLUMN IF NOT EXISTS disk_custom_mode VARCHAR(16) NOT NULL DEFAULT 'unlimited';
ALTER TABLE products ADD COLUMN IF NOT EXISTS disk_tiers JSONB NOT NULL DEFAULT '[]';
ALTER TABLE products ADD COLUMN IF NOT EXISTS disk_unit_price_cents BIGINT NOT NULL DEFAULT 0;

-- 数据盘配置
ALTER TABLE products ADD COLUMN IF NOT EXISTS data_disk_min_mb INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS data_disk_max_mb INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS data_disk_custom_mode VARCHAR(16) NOT NULL DEFAULT 'unlimited';
ALTER TABLE products ADD COLUMN IF NOT EXISTS data_disk_tiers JSONB NOT NULL DEFAULT '[]';
ALTER TABLE products ADD COLUMN IF NOT EXISTS data_disk_unit_price_cents BIGINT NOT NULL DEFAULT 0;

-- 网络带宽配置
ALTER TABLE products ADD COLUMN IF NOT EXISTS network_down_min_mbps INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS network_down_max_mbps INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS network_up_min_mbps INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS network_up_max_mbps INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS network_down_unit_price_cents BIGINT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS network_up_unit_price_cents BIGINT NOT NULL DEFAULT 0;

-- 流量配置
ALTER TABLE products ADD COLUMN IF NOT EXISTS traffic_min_gb INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS traffic_max_gb INT NOT NULL DEFAULT 0;

-- 网桥配置
ALTER TABLE products ADD COLUMN IF NOT EXISTS node_bridges JSONB NOT NULL DEFAULT '{}';
