ALTER TABLE users DROP COLUMN IF EXISTS phone;
ALTER TABLE users DROP COLUMN IF EXISTS qq;
ALTER TABLE users DROP COLUMN IF EXISTS real_name_status;
ALTER TABLE users DROP COLUMN IF EXISTS real_name;
ALTER TABLE users DROP COLUMN IF EXISTS id_card;
